//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSim.B_Kayit {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tckk/MernisIslemleri", ConfigurationName="B_Kayit.MernisIslemleriWSInt")]
    public interface MernisIslemleriWSInt {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PSim.B_Kayit.basvuruIptalEtResponse basvuruIptalEt(PSim.B_Kayit.basvuruIptalEt request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PSim.B_Kayit.basvuruIptalEtResponse> basvuruIptalEtAsync(PSim.B_Kayit.basvuruIptalEt request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PSim.B_Kayit.pttTeslimBilgisiKaydetResponse pttTeslimBilgisiKaydet(PSim.B_Kayit.pttTeslimBilgisiKaydet request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PSim.B_Kayit.pttTeslimBilgisiKaydetResponse> pttTeslimBilgisiKaydetAsync(PSim.B_Kayit.pttTeslimBilgisiKaydet request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PSim.B_Kayit.hataKaydetResponse hataKaydet(PSim.B_Kayit.hataKaydet request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PSim.B_Kayit.hataKaydetResponse> hataKaydetAsync(PSim.B_Kayit.hataKaydet request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PSim.B_Kayit.basvuruKaydetResponse basvuruKaydet(PSim.B_Kayit.basvuruKaydet request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PSim.B_Kayit.basvuruKaydetResponse> basvuruKaydetAsync(PSim.B_Kayit.basvuruKaydet request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        PSim.B_Kayit.basvuruDurumSorgulaResponse basvuruDurumSorgula(PSim.B_Kayit.basvuruDurumSorgula request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PSim.B_Kayit.basvuruDurumSorgulaResponse> basvuruDurumSorgulaAsync(PSim.B_Kayit.basvuruDurumSorgula request);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(basvuruDurumSorgulaSonuc))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(pttTeslimBilgisiSonuc))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tckk/MernisIslemleri")]
    public partial class standartWSSonuc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool basariliField;
        
        private string hataAciklamaField;
        
        private int hataKoduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool basarili {
            get {
                return this.basariliField;
            }
            set {
                this.basariliField = value;
                this.RaisePropertyChanged("basarili");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string hataAciklama {
            get {
                return this.hataAciklamaField;
            }
            set {
                this.hataAciklamaField = value;
                this.RaisePropertyChanged("hataAciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int hataKodu {
            get {
                return this.hataKoduField;
            }
            set {
                this.hataKoduField = value;
                this.RaisePropertyChanged("hataKodu");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tckk/MernisIslemleri")]
    public partial class tckkBasvuru : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string adiField;
        
        private int aliciMernisBirimKoduField;
        
        private bool aliciMernisBirimKoduFieldSpecified;
        
        private long basvuruPostaTakipKodField;
        
        private bool basvuruPostaTakipKodFieldSpecified;
        
        private bool bvysOnayMuafField;
        
        private bool bvysOnayMuafFieldSpecified;
        
        private string cepTelefonNumarasiField;
        
        private cinsiyet cinsiyetField;
        
        private bool cinsiyetFieldSpecified;
        
        private int dogumAyField;
        
        private bool dogumAyFieldSpecified;
        
        private int dogumGunField;
        
        private bool dogumGunFieldSpecified;
        
        private string dogumYeriField;
        
        private int dogumYilField;
        
        private bool dogumYilFieldSpecified;
        
        private int duzenlenmeTarihiAyField;
        
        private bool duzenlenmeTarihiAyFieldSpecified;
        
        private int duzenlenmeTarihiGunField;
        
        private bool duzenlenmeTarihiGunFieldSpecified;
        
        private int duzenlenmeTarihiYilField;
        
        private bool duzenlenmeTarihiYilFieldSpecified;
        
        private string formatlanmisDogumTarihiField;
        
        private string formatlanmisDuzenlenmeTarihiField;
        
        private string formatlanmisSonGecerlilikTarihiField;
        
        private byte[] fotografField;
        
        private byte[] fotografIcaoTokenImageField;
        
        private int iadeMernisBirimKoduField;
        
        private bool iadeMernisBirimKoduFieldSpecified;
        
        private string icaoTokenImageTypeField;
        
        private byte[] islakImzaField;
        
        private string kpsAdresField;
        
        private string mernisAciklamaField;
        
        private string mernisIslemIdField;
        
        private string meslekField;
        
        private string mrzLineField;
        
        private basvuruOncelik oncelikField;
        
        private bool oncelikFieldSpecified;
        
        private pasaportTuru pasaportTuruField;
        
        private bool pasaportTuruFieldSpecified;
        
        private int sonGecerlilikTarihiAyField;
        
        private bool sonGecerlilikTarihiAyFieldSpecified;
        
        private int sonGecerlilikTarihiGunField;
        
        private bool sonGecerlilikTarihiGunFieldSpecified;
        
        private int sonGecerlilikTarihiYilField;
        
        private bool sonGecerlilikTarihiYilFieldSpecified;
        
        private string soyadiField;
        
        private long tckNoField;
        
        private bool tckNoFieldSpecified;
        
        private string telefonNumarasiField;
        
        private string teslimAliciAdresiSatir1Field;
        
        private string teslimAliciAdresiSatir2Field;
        
        private string teslimAliciAdresiSatir3Field;
        
        private string teslimAliciAdresiSatir4Field;
        
        private string teslimKisi2AdField;
        
        private string teslimKisi2SoyadField;
        
        private string teslimKisiAdField;
        
        private string teslimKisiSoyadField;
        
        private teslimSekli teslimSekliField;
        
        private bool teslimSekliFieldSpecified;
        
        private string titleField;
        
        private string unvanField;
        
        private string uyruguField;
        
        private string verenMakamField;
        
        private string vizAdiField;
        
        private string vizSoyadiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string adi {
            get {
                return this.adiField;
            }
            set {
                this.adiField = value;
                this.RaisePropertyChanged("adi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int aliciMernisBirimKodu {
            get {
                return this.aliciMernisBirimKoduField;
            }
            set {
                this.aliciMernisBirimKoduField = value;
                this.RaisePropertyChanged("aliciMernisBirimKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool aliciMernisBirimKoduSpecified {
            get {
                return this.aliciMernisBirimKoduFieldSpecified;
            }
            set {
                this.aliciMernisBirimKoduFieldSpecified = value;
                this.RaisePropertyChanged("aliciMernisBirimKoduSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long basvuruPostaTakipKod {
            get {
                return this.basvuruPostaTakipKodField;
            }
            set {
                this.basvuruPostaTakipKodField = value;
                this.RaisePropertyChanged("basvuruPostaTakipKod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool basvuruPostaTakipKodSpecified {
            get {
                return this.basvuruPostaTakipKodFieldSpecified;
            }
            set {
                this.basvuruPostaTakipKodFieldSpecified = value;
                this.RaisePropertyChanged("basvuruPostaTakipKodSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool bvysOnayMuaf {
            get {
                return this.bvysOnayMuafField;
            }
            set {
                this.bvysOnayMuafField = value;
                this.RaisePropertyChanged("bvysOnayMuaf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bvysOnayMuafSpecified {
            get {
                return this.bvysOnayMuafFieldSpecified;
            }
            set {
                this.bvysOnayMuafFieldSpecified = value;
                this.RaisePropertyChanged("bvysOnayMuafSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string cepTelefonNumarasi {
            get {
                return this.cepTelefonNumarasiField;
            }
            set {
                this.cepTelefonNumarasiField = value;
                this.RaisePropertyChanged("cepTelefonNumarasi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public cinsiyet cinsiyet {
            get {
                return this.cinsiyetField;
            }
            set {
                this.cinsiyetField = value;
                this.RaisePropertyChanged("cinsiyet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cinsiyetSpecified {
            get {
                return this.cinsiyetFieldSpecified;
            }
            set {
                this.cinsiyetFieldSpecified = value;
                this.RaisePropertyChanged("cinsiyetSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int dogumAy {
            get {
                return this.dogumAyField;
            }
            set {
                this.dogumAyField = value;
                this.RaisePropertyChanged("dogumAy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dogumAySpecified {
            get {
                return this.dogumAyFieldSpecified;
            }
            set {
                this.dogumAyFieldSpecified = value;
                this.RaisePropertyChanged("dogumAySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int dogumGun {
            get {
                return this.dogumGunField;
            }
            set {
                this.dogumGunField = value;
                this.RaisePropertyChanged("dogumGun");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dogumGunSpecified {
            get {
                return this.dogumGunFieldSpecified;
            }
            set {
                this.dogumGunFieldSpecified = value;
                this.RaisePropertyChanged("dogumGunSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string dogumYeri {
            get {
                return this.dogumYeriField;
            }
            set {
                this.dogumYeriField = value;
                this.RaisePropertyChanged("dogumYeri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int dogumYil {
            get {
                return this.dogumYilField;
            }
            set {
                this.dogumYilField = value;
                this.RaisePropertyChanged("dogumYil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dogumYilSpecified {
            get {
                return this.dogumYilFieldSpecified;
            }
            set {
                this.dogumYilFieldSpecified = value;
                this.RaisePropertyChanged("dogumYilSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int duzenlenmeTarihiAy {
            get {
                return this.duzenlenmeTarihiAyField;
            }
            set {
                this.duzenlenmeTarihiAyField = value;
                this.RaisePropertyChanged("duzenlenmeTarihiAy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool duzenlenmeTarihiAySpecified {
            get {
                return this.duzenlenmeTarihiAyFieldSpecified;
            }
            set {
                this.duzenlenmeTarihiAyFieldSpecified = value;
                this.RaisePropertyChanged("duzenlenmeTarihiAySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int duzenlenmeTarihiGun {
            get {
                return this.duzenlenmeTarihiGunField;
            }
            set {
                this.duzenlenmeTarihiGunField = value;
                this.RaisePropertyChanged("duzenlenmeTarihiGun");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool duzenlenmeTarihiGunSpecified {
            get {
                return this.duzenlenmeTarihiGunFieldSpecified;
            }
            set {
                this.duzenlenmeTarihiGunFieldSpecified = value;
                this.RaisePropertyChanged("duzenlenmeTarihiGunSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int duzenlenmeTarihiYil {
            get {
                return this.duzenlenmeTarihiYilField;
            }
            set {
                this.duzenlenmeTarihiYilField = value;
                this.RaisePropertyChanged("duzenlenmeTarihiYil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool duzenlenmeTarihiYilSpecified {
            get {
                return this.duzenlenmeTarihiYilFieldSpecified;
            }
            set {
                this.duzenlenmeTarihiYilFieldSpecified = value;
                this.RaisePropertyChanged("duzenlenmeTarihiYilSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string formatlanmisDogumTarihi {
            get {
                return this.formatlanmisDogumTarihiField;
            }
            set {
                this.formatlanmisDogumTarihiField = value;
                this.RaisePropertyChanged("formatlanmisDogumTarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string formatlanmisDuzenlenmeTarihi {
            get {
                return this.formatlanmisDuzenlenmeTarihiField;
            }
            set {
                this.formatlanmisDuzenlenmeTarihiField = value;
                this.RaisePropertyChanged("formatlanmisDuzenlenmeTarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string formatlanmisSonGecerlilikTarihi {
            get {
                return this.formatlanmisSonGecerlilikTarihiField;
            }
            set {
                this.formatlanmisSonGecerlilikTarihiField = value;
                this.RaisePropertyChanged("formatlanmisSonGecerlilikTarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=16)]
        public byte[] fotograf {
            get {
                return this.fotografField;
            }
            set {
                this.fotografField = value;
                this.RaisePropertyChanged("fotograf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=17)]
        public byte[] fotografIcaoTokenImage {
            get {
                return this.fotografIcaoTokenImageField;
            }
            set {
                this.fotografIcaoTokenImageField = value;
                this.RaisePropertyChanged("fotografIcaoTokenImage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public int iadeMernisBirimKodu {
            get {
                return this.iadeMernisBirimKoduField;
            }
            set {
                this.iadeMernisBirimKoduField = value;
                this.RaisePropertyChanged("iadeMernisBirimKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool iadeMernisBirimKoduSpecified {
            get {
                return this.iadeMernisBirimKoduFieldSpecified;
            }
            set {
                this.iadeMernisBirimKoduFieldSpecified = value;
                this.RaisePropertyChanged("iadeMernisBirimKoduSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string icaoTokenImageType {
            get {
                return this.icaoTokenImageTypeField;
            }
            set {
                this.icaoTokenImageTypeField = value;
                this.RaisePropertyChanged("icaoTokenImageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=20)]
        public byte[] islakImza {
            get {
                return this.islakImzaField;
            }
            set {
                this.islakImzaField = value;
                this.RaisePropertyChanged("islakImza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string kpsAdres {
            get {
                return this.kpsAdresField;
            }
            set {
                this.kpsAdresField = value;
                this.RaisePropertyChanged("kpsAdres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string mernisAciklama {
            get {
                return this.mernisAciklamaField;
            }
            set {
                this.mernisAciklamaField = value;
                this.RaisePropertyChanged("mernisAciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string mernisIslemId {
            get {
                return this.mernisIslemIdField;
            }
            set {
                this.mernisIslemIdField = value;
                this.RaisePropertyChanged("mernisIslemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string meslek {
            get {
                return this.meslekField;
            }
            set {
                this.meslekField = value;
                this.RaisePropertyChanged("meslek");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string mrzLine {
            get {
                return this.mrzLineField;
            }
            set {
                this.mrzLineField = value;
                this.RaisePropertyChanged("mrzLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public basvuruOncelik oncelik {
            get {
                return this.oncelikField;
            }
            set {
                this.oncelikField = value;
                this.RaisePropertyChanged("oncelik");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oncelikSpecified {
            get {
                return this.oncelikFieldSpecified;
            }
            set {
                this.oncelikFieldSpecified = value;
                this.RaisePropertyChanged("oncelikSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public pasaportTuru pasaportTuru {
            get {
                return this.pasaportTuruField;
            }
            set {
                this.pasaportTuruField = value;
                this.RaisePropertyChanged("pasaportTuru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pasaportTuruSpecified {
            get {
                return this.pasaportTuruFieldSpecified;
            }
            set {
                this.pasaportTuruFieldSpecified = value;
                this.RaisePropertyChanged("pasaportTuruSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public int sonGecerlilikTarihiAy {
            get {
                return this.sonGecerlilikTarihiAyField;
            }
            set {
                this.sonGecerlilikTarihiAyField = value;
                this.RaisePropertyChanged("sonGecerlilikTarihiAy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sonGecerlilikTarihiAySpecified {
            get {
                return this.sonGecerlilikTarihiAyFieldSpecified;
            }
            set {
                this.sonGecerlilikTarihiAyFieldSpecified = value;
                this.RaisePropertyChanged("sonGecerlilikTarihiAySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public int sonGecerlilikTarihiGun {
            get {
                return this.sonGecerlilikTarihiGunField;
            }
            set {
                this.sonGecerlilikTarihiGunField = value;
                this.RaisePropertyChanged("sonGecerlilikTarihiGun");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sonGecerlilikTarihiGunSpecified {
            get {
                return this.sonGecerlilikTarihiGunFieldSpecified;
            }
            set {
                this.sonGecerlilikTarihiGunFieldSpecified = value;
                this.RaisePropertyChanged("sonGecerlilikTarihiGunSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public int sonGecerlilikTarihiYil {
            get {
                return this.sonGecerlilikTarihiYilField;
            }
            set {
                this.sonGecerlilikTarihiYilField = value;
                this.RaisePropertyChanged("sonGecerlilikTarihiYil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sonGecerlilikTarihiYilSpecified {
            get {
                return this.sonGecerlilikTarihiYilFieldSpecified;
            }
            set {
                this.sonGecerlilikTarihiYilFieldSpecified = value;
                this.RaisePropertyChanged("sonGecerlilikTarihiYilSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string soyadi {
            get {
                return this.soyadiField;
            }
            set {
                this.soyadiField = value;
                this.RaisePropertyChanged("soyadi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public long tckNo {
            get {
                return this.tckNoField;
            }
            set {
                this.tckNoField = value;
                this.RaisePropertyChanged("tckNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tckNoSpecified {
            get {
                return this.tckNoFieldSpecified;
            }
            set {
                this.tckNoFieldSpecified = value;
                this.RaisePropertyChanged("tckNoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string telefonNumarasi {
            get {
                return this.telefonNumarasiField;
            }
            set {
                this.telefonNumarasiField = value;
                this.RaisePropertyChanged("telefonNumarasi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string teslimAliciAdresiSatir1 {
            get {
                return this.teslimAliciAdresiSatir1Field;
            }
            set {
                this.teslimAliciAdresiSatir1Field = value;
                this.RaisePropertyChanged("teslimAliciAdresiSatir1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string teslimAliciAdresiSatir2 {
            get {
                return this.teslimAliciAdresiSatir2Field;
            }
            set {
                this.teslimAliciAdresiSatir2Field = value;
                this.RaisePropertyChanged("teslimAliciAdresiSatir2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public string teslimAliciAdresiSatir3 {
            get {
                return this.teslimAliciAdresiSatir3Field;
            }
            set {
                this.teslimAliciAdresiSatir3Field = value;
                this.RaisePropertyChanged("teslimAliciAdresiSatir3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public string teslimAliciAdresiSatir4 {
            get {
                return this.teslimAliciAdresiSatir4Field;
            }
            set {
                this.teslimAliciAdresiSatir4Field = value;
                this.RaisePropertyChanged("teslimAliciAdresiSatir4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public string teslimKisi2Ad {
            get {
                return this.teslimKisi2AdField;
            }
            set {
                this.teslimKisi2AdField = value;
                this.RaisePropertyChanged("teslimKisi2Ad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string teslimKisi2Soyad {
            get {
                return this.teslimKisi2SoyadField;
            }
            set {
                this.teslimKisi2SoyadField = value;
                this.RaisePropertyChanged("teslimKisi2Soyad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public string teslimKisiAd {
            get {
                return this.teslimKisiAdField;
            }
            set {
                this.teslimKisiAdField = value;
                this.RaisePropertyChanged("teslimKisiAd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=41)]
        public string teslimKisiSoyad {
            get {
                return this.teslimKisiSoyadField;
            }
            set {
                this.teslimKisiSoyadField = value;
                this.RaisePropertyChanged("teslimKisiSoyad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=42)]
        public teslimSekli teslimSekli {
            get {
                return this.teslimSekliField;
            }
            set {
                this.teslimSekliField = value;
                this.RaisePropertyChanged("teslimSekli");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool teslimSekliSpecified {
            get {
                return this.teslimSekliFieldSpecified;
            }
            set {
                this.teslimSekliFieldSpecified = value;
                this.RaisePropertyChanged("teslimSekliSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=43)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=44)]
        public string unvan {
            get {
                return this.unvanField;
            }
            set {
                this.unvanField = value;
                this.RaisePropertyChanged("unvan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=45)]
        public string uyrugu {
            get {
                return this.uyruguField;
            }
            set {
                this.uyruguField = value;
                this.RaisePropertyChanged("uyrugu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=46)]
        public string verenMakam {
            get {
                return this.verenMakamField;
            }
            set {
                this.verenMakamField = value;
                this.RaisePropertyChanged("verenMakam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=47)]
        public string vizAdi {
            get {
                return this.vizAdiField;
            }
            set {
                this.vizAdiField = value;
                this.RaisePropertyChanged("vizAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=48)]
        public string vizSoyadi {
            get {
                return this.vizSoyadiField;
            }
            set {
                this.vizSoyadiField = value;
                this.RaisePropertyChanged("vizSoyadi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tckk/MernisIslemleri")]
    public enum cinsiyet {
        
        /// <remarks/>
        BILINMEYEN,
        
        /// <remarks/>
        ERKEK,
        
        /// <remarks/>
        KADIN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tckk/MernisIslemleri")]
    public enum basvuruOncelik {
        
        /// <remarks/>
        NORMAL,
        
        /// <remarks/>
        TEKRAR_BASIM,
        
        /// <remarks/>
        ACIL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tckk/MernisIslemleri")]
    public enum pasaportTuru {
        
        /// <remarks/>
        BORDO_PASAPORT,
        
        /// <remarks/>
        YESIL_PASAPORT,
        
        /// <remarks/>
        GRI_PASAPORT,
        
        /// <remarks/>
        DIPLOMATIK_PASAPORT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tckk/MernisIslemleri")]
    public enum teslimSekli {
        
        /// <remarks/>
        PTT_ILE_TESLIM,
        
        /// <remarks/>
        ELDEN_YURTDISINA_TESLIM,
        
        /// <remarks/>
        ELDEN_TESLIM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tckk/MernisIslemleri")]
    public partial class zamanBilgi : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dayField;
        
        private int hourField;
        
        private int minuteField;
        
        private int monthField;
        
        private int secondsField;
        
        private int yearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
                this.RaisePropertyChanged("day");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int hour {
            get {
                return this.hourField;
            }
            set {
                this.hourField = value;
                this.RaisePropertyChanged("hour");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int minute {
            get {
                return this.minuteField;
            }
            set {
                this.minuteField = value;
                this.RaisePropertyChanged("minute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
                this.RaisePropertyChanged("month");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int seconds {
            get {
                return this.secondsField;
            }
            set {
                this.secondsField = value;
                this.RaisePropertyChanged("seconds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tckk/MernisIslemleri")]
    public partial class pttTeslimBilgisiTekilSonuc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool basariliField;
        
        private string hataAciklamaField;
        
        private int hataKoduField;
        
        private string mernisIslemIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool basarili {
            get {
                return this.basariliField;
            }
            set {
                this.basariliField = value;
                this.RaisePropertyChanged("basarili");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string hataAciklama {
            get {
                return this.hataAciklamaField;
            }
            set {
                this.hataAciklamaField = value;
                this.RaisePropertyChanged("hataAciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int hataKodu {
            get {
                return this.hataKoduField;
            }
            set {
                this.hataKoduField = value;
                this.RaisePropertyChanged("hataKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string mernisIslemId {
            get {
                return this.mernisIslemIdField;
            }
            set {
                this.mernisIslemIdField = value;
                this.RaisePropertyChanged("mernisIslemId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tckk/MernisIslemleri")]
    public partial class basvuruDurumSorgulaSonuc : standartWSSonuc {
        
        private string basvuruDurumAciklamaField;
        
        private int basvuruDurumKodField;
        
        private bool basvuruDurumKodFieldSpecified;
        
        private zamanBilgi basvuruTarihField;
        
        private string kartDurumAciklamaField;
        
        private int kartDurumKodField;
        
        private bool kartDurumKodFieldSpecified;
        
        private string kartSeriNoField;
        
        private long postaTakipKoduField;
        
        private bool postaTakipKoduFieldSpecified;
        
        private long tcKimlikNoField;
        
        private bool tcKimlikNoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string basvuruDurumAciklama {
            get {
                return this.basvuruDurumAciklamaField;
            }
            set {
                this.basvuruDurumAciklamaField = value;
                this.RaisePropertyChanged("basvuruDurumAciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int basvuruDurumKod {
            get {
                return this.basvuruDurumKodField;
            }
            set {
                this.basvuruDurumKodField = value;
                this.RaisePropertyChanged("basvuruDurumKod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool basvuruDurumKodSpecified {
            get {
                return this.basvuruDurumKodFieldSpecified;
            }
            set {
                this.basvuruDurumKodFieldSpecified = value;
                this.RaisePropertyChanged("basvuruDurumKodSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public zamanBilgi basvuruTarih {
            get {
                return this.basvuruTarihField;
            }
            set {
                this.basvuruTarihField = value;
                this.RaisePropertyChanged("basvuruTarih");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string kartDurumAciklama {
            get {
                return this.kartDurumAciklamaField;
            }
            set {
                this.kartDurumAciklamaField = value;
                this.RaisePropertyChanged("kartDurumAciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int kartDurumKod {
            get {
                return this.kartDurumKodField;
            }
            set {
                this.kartDurumKodField = value;
                this.RaisePropertyChanged("kartDurumKod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool kartDurumKodSpecified {
            get {
                return this.kartDurumKodFieldSpecified;
            }
            set {
                this.kartDurumKodFieldSpecified = value;
                this.RaisePropertyChanged("kartDurumKodSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string kartSeriNo {
            get {
                return this.kartSeriNoField;
            }
            set {
                this.kartSeriNoField = value;
                this.RaisePropertyChanged("kartSeriNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long postaTakipKodu {
            get {
                return this.postaTakipKoduField;
            }
            set {
                this.postaTakipKoduField = value;
                this.RaisePropertyChanged("postaTakipKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool postaTakipKoduSpecified {
            get {
                return this.postaTakipKoduFieldSpecified;
            }
            set {
                this.postaTakipKoduFieldSpecified = value;
                this.RaisePropertyChanged("postaTakipKoduSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long tcKimlikNo {
            get {
                return this.tcKimlikNoField;
            }
            set {
                this.tcKimlikNoField = value;
                this.RaisePropertyChanged("tcKimlikNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tcKimlikNoSpecified {
            get {
                return this.tcKimlikNoFieldSpecified;
            }
            set {
                this.tcKimlikNoFieldSpecified = value;
                this.RaisePropertyChanged("tcKimlikNoSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tckk/MernisIslemleri")]
    public partial class pttTeslimBilgisiSonuc : standartWSSonuc {
        
        private pttTeslimBilgisiTekilSonuc[] pttTeslimBilgisiTekilSonucListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("pttTeslimBilgisiTekilSonucList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public pttTeslimBilgisiTekilSonuc[] pttTeslimBilgisiTekilSonucList {
            get {
                return this.pttTeslimBilgisiTekilSonucListField;
            }
            set {
                this.pttTeslimBilgisiTekilSonucListField = value;
                this.RaisePropertyChanged("pttTeslimBilgisiTekilSonucList");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="basvuruIptalEt", WrapperNamespace="http://tckk/MernisIslemleri", IsWrapped=true)]
    public partial class basvuruIptalEt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tckk/MernisIslemleri", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mernisIslemId;
        
        public basvuruIptalEt() {
        }
        
        public basvuruIptalEt(string mernisIslemId) {
            this.mernisIslemId = mernisIslemId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="basvuruIptalEtResponse", WrapperNamespace="http://tckk/MernisIslemleri", IsWrapped=true)]
    public partial class basvuruIptalEtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tckk/MernisIslemleri", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PSim.B_Kayit.standartWSSonuc @return;
        
        public basvuruIptalEtResponse() {
        }
        
        public basvuruIptalEtResponse(PSim.B_Kayit.standartWSSonuc @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pttTeslimBilgisiKaydet", WrapperNamespace="http://tckk/MernisIslemleri", IsWrapped=true)]
    public partial class pttTeslimBilgisiKaydet {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tckk/MernisIslemleri", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("mernisIslemIdList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] pttTeslimBilgisi;
        
        public pttTeslimBilgisiKaydet() {
        }
        
        public pttTeslimBilgisiKaydet(string[] pttTeslimBilgisi) {
            this.pttTeslimBilgisi = pttTeslimBilgisi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pttTeslimBilgisiKaydetResponse", WrapperNamespace="http://tckk/MernisIslemleri", IsWrapped=true)]
    public partial class pttTeslimBilgisiKaydetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tckk/MernisIslemleri", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PSim.B_Kayit.pttTeslimBilgisiSonuc @return;
        
        public pttTeslimBilgisiKaydetResponse() {
        }
        
        public pttTeslimBilgisiKaydetResponse(PSim.B_Kayit.pttTeslimBilgisiSonuc @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hataKaydet", WrapperNamespace="http://tckk/MernisIslemleri", IsWrapped=true)]
    public partial class hataKaydet {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tckk/MernisIslemleri", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WebServisAd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tckk/MernisIslemleri", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Aciklama;
        
        public hataKaydet() {
        }
        
        public hataKaydet(string WebServisAd, string Aciklama) {
            this.WebServisAd = WebServisAd;
            this.Aciklama = Aciklama;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hataKaydetResponse", WrapperNamespace="http://tckk/MernisIslemleri", IsWrapped=true)]
    public partial class hataKaydetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tckk/MernisIslemleri", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PSim.B_Kayit.standartWSSonuc @return;
        
        public hataKaydetResponse() {
        }
        
        public hataKaydetResponse(PSim.B_Kayit.standartWSSonuc @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="basvuruKaydet", WrapperNamespace="http://tckk/MernisIslemleri", IsWrapped=true)]
    public partial class basvuruKaydet {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tckk/MernisIslemleri", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PSim.B_Kayit.tckkBasvuru tckkBasvuru;
        
        public basvuruKaydet() {
        }
        
        public basvuruKaydet(PSim.B_Kayit.tckkBasvuru tckkBasvuru) {
            this.tckkBasvuru = tckkBasvuru;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="basvuruKaydetResponse", WrapperNamespace="http://tckk/MernisIslemleri", IsWrapped=true)]
    public partial class basvuruKaydetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tckk/MernisIslemleri", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PSim.B_Kayit.standartWSSonuc @return;
        
        public basvuruKaydetResponse() {
        }
        
        public basvuruKaydetResponse(PSim.B_Kayit.standartWSSonuc @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="basvuruDurumSorgula", WrapperNamespace="http://tckk/MernisIslemleri", IsWrapped=true)]
    public partial class basvuruDurumSorgula {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tckk/MernisIslemleri", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mernisIslemId;
        
        public basvuruDurumSorgula() {
        }
        
        public basvuruDurumSorgula(string mernisIslemId) {
            this.mernisIslemId = mernisIslemId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="basvuruDurumSorgulaResponse", WrapperNamespace="http://tckk/MernisIslemleri", IsWrapped=true)]
    public partial class basvuruDurumSorgulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tckk/MernisIslemleri", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PSim.B_Kayit.basvuruDurumSorgulaSonuc @return;
        
        public basvuruDurumSorgulaResponse() {
        }
        
        public basvuruDurumSorgulaResponse(PSim.B_Kayit.basvuruDurumSorgulaSonuc @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MernisIslemleriWSIntChannel : PSim.B_Kayit.MernisIslemleriWSInt, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MernisIslemleriWSIntClient : System.ServiceModel.ClientBase<PSim.B_Kayit.MernisIslemleriWSInt>, PSim.B_Kayit.MernisIslemleriWSInt {
        
        public MernisIslemleriWSIntClient() {
        }
        
        public MernisIslemleriWSIntClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MernisIslemleriWSIntClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MernisIslemleriWSIntClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MernisIslemleriWSIntClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PSim.B_Kayit.basvuruIptalEtResponse PSim.B_Kayit.MernisIslemleriWSInt.basvuruIptalEt(PSim.B_Kayit.basvuruIptalEt request) {
            return base.Channel.basvuruIptalEt(request);
        }
        
        public PSim.B_Kayit.standartWSSonuc basvuruIptalEt(string mernisIslemId) {
            PSim.B_Kayit.basvuruIptalEt inValue = new PSim.B_Kayit.basvuruIptalEt();
            inValue.mernisIslemId = mernisIslemId;
            PSim.B_Kayit.basvuruIptalEtResponse retVal = ((PSim.B_Kayit.MernisIslemleriWSInt)(this)).basvuruIptalEt(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PSim.B_Kayit.basvuruIptalEtResponse> PSim.B_Kayit.MernisIslemleriWSInt.basvuruIptalEtAsync(PSim.B_Kayit.basvuruIptalEt request) {
            return base.Channel.basvuruIptalEtAsync(request);
        }
        
        public System.Threading.Tasks.Task<PSim.B_Kayit.basvuruIptalEtResponse> basvuruIptalEtAsync(string mernisIslemId) {
            PSim.B_Kayit.basvuruIptalEt inValue = new PSim.B_Kayit.basvuruIptalEt();
            inValue.mernisIslemId = mernisIslemId;
            return ((PSim.B_Kayit.MernisIslemleriWSInt)(this)).basvuruIptalEtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PSim.B_Kayit.pttTeslimBilgisiKaydetResponse PSim.B_Kayit.MernisIslemleriWSInt.pttTeslimBilgisiKaydet(PSim.B_Kayit.pttTeslimBilgisiKaydet request) {
            return base.Channel.pttTeslimBilgisiKaydet(request);
        }
        
        public PSim.B_Kayit.pttTeslimBilgisiSonuc pttTeslimBilgisiKaydet(string[] pttTeslimBilgisi) {
            PSim.B_Kayit.pttTeslimBilgisiKaydet inValue = new PSim.B_Kayit.pttTeslimBilgisiKaydet();
            inValue.pttTeslimBilgisi = pttTeslimBilgisi;
            PSim.B_Kayit.pttTeslimBilgisiKaydetResponse retVal = ((PSim.B_Kayit.MernisIslemleriWSInt)(this)).pttTeslimBilgisiKaydet(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PSim.B_Kayit.pttTeslimBilgisiKaydetResponse> PSim.B_Kayit.MernisIslemleriWSInt.pttTeslimBilgisiKaydetAsync(PSim.B_Kayit.pttTeslimBilgisiKaydet request) {
            return base.Channel.pttTeslimBilgisiKaydetAsync(request);
        }
        
        public System.Threading.Tasks.Task<PSim.B_Kayit.pttTeslimBilgisiKaydetResponse> pttTeslimBilgisiKaydetAsync(string[] pttTeslimBilgisi) {
            PSim.B_Kayit.pttTeslimBilgisiKaydet inValue = new PSim.B_Kayit.pttTeslimBilgisiKaydet();
            inValue.pttTeslimBilgisi = pttTeslimBilgisi;
            return ((PSim.B_Kayit.MernisIslemleriWSInt)(this)).pttTeslimBilgisiKaydetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PSim.B_Kayit.hataKaydetResponse PSim.B_Kayit.MernisIslemleriWSInt.hataKaydet(PSim.B_Kayit.hataKaydet request) {
            return base.Channel.hataKaydet(request);
        }
        
        public PSim.B_Kayit.standartWSSonuc hataKaydet(string WebServisAd, string Aciklama) {
            PSim.B_Kayit.hataKaydet inValue = new PSim.B_Kayit.hataKaydet();
            inValue.WebServisAd = WebServisAd;
            inValue.Aciklama = Aciklama;
            PSim.B_Kayit.hataKaydetResponse retVal = ((PSim.B_Kayit.MernisIslemleriWSInt)(this)).hataKaydet(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PSim.B_Kayit.hataKaydetResponse> PSim.B_Kayit.MernisIslemleriWSInt.hataKaydetAsync(PSim.B_Kayit.hataKaydet request) {
            return base.Channel.hataKaydetAsync(request);
        }
        
        public System.Threading.Tasks.Task<PSim.B_Kayit.hataKaydetResponse> hataKaydetAsync(string WebServisAd, string Aciklama) {
            PSim.B_Kayit.hataKaydet inValue = new PSim.B_Kayit.hataKaydet();
            inValue.WebServisAd = WebServisAd;
            inValue.Aciklama = Aciklama;
            return ((PSim.B_Kayit.MernisIslemleriWSInt)(this)).hataKaydetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PSim.B_Kayit.basvuruKaydetResponse PSim.B_Kayit.MernisIslemleriWSInt.basvuruKaydet(PSim.B_Kayit.basvuruKaydet request) {
            return base.Channel.basvuruKaydet(request);
        }
        
        public PSim.B_Kayit.standartWSSonuc basvuruKaydet(PSim.B_Kayit.tckkBasvuru tckkBasvuru) {
            PSim.B_Kayit.basvuruKaydet inValue = new PSim.B_Kayit.basvuruKaydet();
            inValue.tckkBasvuru = tckkBasvuru;
            PSim.B_Kayit.basvuruKaydetResponse retVal = ((PSim.B_Kayit.MernisIslemleriWSInt)(this)).basvuruKaydet(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PSim.B_Kayit.basvuruKaydetResponse> PSim.B_Kayit.MernisIslemleriWSInt.basvuruKaydetAsync(PSim.B_Kayit.basvuruKaydet request) {
            return base.Channel.basvuruKaydetAsync(request);
        }
        
        public System.Threading.Tasks.Task<PSim.B_Kayit.basvuruKaydetResponse> basvuruKaydetAsync(PSim.B_Kayit.tckkBasvuru tckkBasvuru) {
            PSim.B_Kayit.basvuruKaydet inValue = new PSim.B_Kayit.basvuruKaydet();
            inValue.tckkBasvuru = tckkBasvuru;
            return ((PSim.B_Kayit.MernisIslemleriWSInt)(this)).basvuruKaydetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PSim.B_Kayit.basvuruDurumSorgulaResponse PSim.B_Kayit.MernisIslemleriWSInt.basvuruDurumSorgula(PSim.B_Kayit.basvuruDurumSorgula request) {
            return base.Channel.basvuruDurumSorgula(request);
        }
        
        public PSim.B_Kayit.basvuruDurumSorgulaSonuc basvuruDurumSorgula(string mernisIslemId) {
            PSim.B_Kayit.basvuruDurumSorgula inValue = new PSim.B_Kayit.basvuruDurumSorgula();
            inValue.mernisIslemId = mernisIslemId;
            PSim.B_Kayit.basvuruDurumSorgulaResponse retVal = ((PSim.B_Kayit.MernisIslemleriWSInt)(this)).basvuruDurumSorgula(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PSim.B_Kayit.basvuruDurumSorgulaResponse> PSim.B_Kayit.MernisIslemleriWSInt.basvuruDurumSorgulaAsync(PSim.B_Kayit.basvuruDurumSorgula request) {
            return base.Channel.basvuruDurumSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PSim.B_Kayit.basvuruDurumSorgulaResponse> basvuruDurumSorgulaAsync(string mernisIslemId) {
            PSim.B_Kayit.basvuruDurumSorgula inValue = new PSim.B_Kayit.basvuruDurumSorgula();
            inValue.mernisIslemId = mernisIslemId;
            return ((PSim.B_Kayit.MernisIslemleriWSInt)(this)).basvuruDurumSorgulaAsync(inValue);
        }
    }
}
